### PR TITLE
Rename to Web: update repository name in tests and staging

### PR DESCRIPTION
**Pull request by carlosms**
Part of #218.

Changes the repository name for drone, travis, and staging.

### CODE REVIEW

**Comment by bzz** [comment]
👍 Would this possibly require any changes on Drone side? 

\cc @rporres

**Comment by bzz** [comment]
@carlosms as CI is failing, it seems like we might have a test that is flaky - do you think we should
 - check if this tests pass locally on this branch
 - not restart the job on Travis, so we have could have a link to failing tests (keep an evidence)
 - create a new issue about particular test being flaky, and attaching a link to Travis there

WDYT?

```
=== RUN   TestExportIntegrationSuite/TestSuccess
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
goroutine 74 [running]:
testing.tRunner.func1(0xc420be8f00)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/testing/testing.go:742 +0x29d
panic(0xaa2aa0, 0x1665120)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/src-d/gitbase-playground/server/handler_test.(*ExportIntegrationSuite).TestSuccess(0xc421450060)
	/home/travis/gopath/src/github.com/src-d/gitbase-playground/server/handler/export_integration_test.go:59 +0x642
reflect.Value.call(0xc4216f6e40, 0xc421456b88, 0x13, 0xb67fa5, 0x4, 0xc42005ff80, 0x1, 0x1, 0xc42004aec8, 0xb5acc0, ...)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4216f6e40, 0xc421456b88, 0x13, 0xc42004af80, 0x1, 0x1, 0xa00943, 0xb, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/src-d/gitbase-playground/vendor/github.com/stretchr/testify/suite.Run.func2(0xc420be8f00)
	/home/travis/gopath/src/github.com/src-d/gitbase-playground/vendor/github.com/stretchr/testify/suite/suite.go:102 +0x243
testing.tRunner(0xc420be8f00, 0xc421746380)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/testing/testing.go:824 +0x2e0
FAIL	github.com/src-d/gitbase-playground/server/handler	0.066s
```

**Comment by carlosms** [comment]
That integration test is failing because travis is not able to clone the git repo with the new name. I've pushed a change in b73bd17 to make it fail gracefully instead of panicking, but it won't pass until the repo is renamed.

For reference. Build that @bzz is referring to: https://travis-ci.org/src-d/gitbase-playground/jobs/417221659
Latest build after b73bd17: https://travis-ci.org/src-d/gitbase-playground/jobs/417272427

**Comment by rporres** [comment]
> Would this possibly require any changes on Drone side?

It looks drone have been automagically updated. I'm more worried about the possible domain changes

**Pull request merged**
