### PR TITLE
Remove Drone

### PR DESCRIPTION
**Pull request by meyskens**
This removes the Drone integration as we're decommissioning Drone

### CODE REVIEW

**Comment by rporres** [comment]
cc @src-d/applications

**Comment by dpordomingo** [comment]
Are we still supporting this project? Didn't it stale when we started working in source{d}?

**Comment by rporres** [comment]
That's why we're not migrating it to Travis, @dpordomingo

**Comment by dpordomingo** [comment]
If we merge, http://gitbase-playground-staging.srcd.run will become stale and we won't be able to deploy a new version, what lgtm.

I wonder if we could also turn the service itself off, or we might confirm it in advance with @src-d/product

**Pull request merged**
