### PR TITLE
Modifies Makefile in order to include bin for OSX and Windows

### LINKED ISSUE #301: Build and release binaries for macOS and windows
Older versions of libuast prevented us from building other platform that linux. Now that we use bblfsh/client-go v3 (#279) we should be able to build and release the binaries for macOS and windows.

### PR DESCRIPTION
**Pull request by se7entyse7en**
Closes #301.

### CODE REVIEW

**Comment by carlosms** [comment]
Did you test if the binaries built on linux work for macOS and windows?

**Comment by smacker** [comment]
why is it necessary to test without cgo?

**Comment by carlosms** [comment]
why not? It _should_ work, but it would be nice to know that it works as expected.

**Comment by smacker** [comment]
idk. Go guarantees it will work as long as we don't use cgo and don't rely on any external dependencies (like docker for engine) or don't use anything os specific (like file paths in lookout)

**Comment by se7entyse7en** [comment]
@carlosms I've tested the OSX binary, but I haven't the windows one.

**Pull request merged**
